### ISSUE TITLE
Widget render problem

### ISSUE THREAD

**Issue by chubz** [abogushov/django-admin-json-editor#14]
Hi,
I had a problem with rendering the widget with any dict schema passed.
My project uses py2.7 and django 1.11.10

It seems that when pure dict is passed to the context it doesn't turn into a json string that schema attribute for the JS part likes to render.
it turns into a string that contains {**u**'title': 'sometitle'}

I've added json.dumps to assure json string is sent to the context and now widget renders the schema properly, and made a pull request #13

**Comment by abogushov** [comment]
@chubz merged. Thanks!
