### ISSUE TITLE
Use other widgets within json editor

### ISSUE THREAD

**Issue by Fandekasp** [abogushov/django-admin-json-editor#16]
Is it possible to use other widgets, let's say an ImageField on one of the json schema properties ie a string format url ?

**Comment by abogushov** [comment]
@Fandekasp There are few widgets that supported by json-editor. See https://github.com/json-editor/json-editor.

- A compatible JS template engine (Mustache, Underscore, Hogan, Handlebars, Swig, Markup, or EJS)
- A compatible CSS framework for styling (bootstrap 2/3, foundation 3/4/5, or jqueryui)
- A compatible icon library (bootstrap 2/3 glyphicons, foundation icons 2/3, jqueryui, or font awesome 3/4)
- SCEditor for WYSIWYG editing of HTML or BBCode content
- SimpleMDE for editing of Markdown content
- Ace Editor for editing code
- Select2 for nicer Select boxes
- Selectize for nicer Select & Array boxes
- math.js for more accurate floating point math (multipleOf, divisibleBy, etc.)

**Comment by abogushov** [comment]
I guess it is not possible to integrate other Django widgets to edit fields of JSONField.

**Comment by Fandekasp** [comment]
Roger it, thanks for the reply!
