### ISSUE TITLE
jdorn/json-editor is deprecated

### ISSUE THREAD

**Issue by AdrienLemaire** [abogushov/django-admin-json-editor#17]
Just realized when clicking on your readme link that the underlying [jdorn/json-editor](https://github.com/jdorn/json-editor) repository has been deprecated, and updates are now done on [json-editor/json-editor](https://github.com/json-editor/json-editor). 

Have you updated the static files with those from that new repo ?
Also, wouldn't it be simpler to use their cdn instead of copying the file ?
```
<script src="https://cdn.jsdelivr.net/npm/@json-editor/json-editor/dist/jsoneditor.min.js"></script>
```

**Comment by abogushov** [comment]
@Fandekasp thanks, I will update static files in the repo. Also I can make optional support for CDN.

**Comment by xrmx** [comment]
json-editor has been updated to latest in master

**Comment by abogushov** [comment]
done
