### ISSUE TITLE
fontawesome4 not loaded

### ISSUE THREAD

**Issue by Fandekasp** [abogushov/django-admin-json-editor#2]
Since you auto set the iconlib to fontawesome4, can you also add the django-fontawesome (or django-font-awesome?) dependency to the plugin ? Icons aren't showing to the user if he doesn't have the font installed on his system.

**Comment by abogushov** [comment]
Hello, I have added [fontawesome4](https://github.com/abogushov/django-admin-json-editor/tree/master/django_admin_json_editor/static/django_admin_json_editor/fontawesome) as static for the application so it must work.

**Comment by Fandekasp** [comment]
Sorry, got too busy and forgot to update this. Yes, I had forgotten to
collectstatic. Tnx a bunch!

**Comment by abogushov** [comment]
Nice!
